version: '3.4'

services:
  api:
    build: .
    image: fragments-api
    ports:
    - '8080:8080'
    volumes:
      - './:/go/src/github.com/bluebrown/fragments/'
    command:
      - go
      - run
      - .

  store:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - "./data:/data"
    entrypoint:
      - redis-server
      - --appendonly yes
