# Flat GraphQL schema.
schema {
    query: Query
}

type Query {
    user(Name: String!): User!
    users: [User!]!
    message: Message!
    messages: [Message!]!
}

type User {
    name: String!
    mail: String!
}

type Message {
    text: String!
    from: User!
    to: [User!]!
}