# Flat GraphQL schema.
schema {
    query: Query
}

type Query {
    user(Name: String!): User!
    users: [User!]!
    message: Message!
    messages: [Message!]!
}

type User {
    name: String!
    mail: String!
}

type Message{#TODO: Represent from-to with a graphQL edge (One-To-Many).
    text: String!
    from: User!
    to: [User!]!
}
